apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: estadisticas-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: estadisticas-service
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60   # baja pods tras 60s de calma (no 300s por defecto)
    scaleUp:
      stabilizationWindowSeconds: 0    # sube de inmediato ante un pico